index:
    path: /
    controller: App\Controller\IndexController::home

homepage:
 path: /article_list
 controller: App\Controller\IndexController::home

article_save:
    path: /article/save
    controller: App\Controller\IndexController::save

new_article:
    path: /article/new
    controller: App\Controller\IndexController::new
    methods: [GET, POST]

article_show:
    path: /article/{id}
    controller: App\Controller\IndexController::show

edit_article:
  path: '/article/edit/{id}'
  controller: App\Controller\IndexController::edit
  methods: ['GET', 'POST']

delete_article:
  path: '/article/delete/{id}'
  controller: App\Controller\IndexController::delete
  methods: ['DELETE','GET']

article_list:
 path: /article_list
 controller: App\Controller\IndexController::home

new_category:
  path: /category/newCat
  controller: App\Controller\IndexController::newCategory
  methods: [GET, POST]

article_par_cat:
    path: /art_cat/
    methods: [GET, POST]
    controller: App\Controller\IndexController::articlesParCategorie

article_par_prix:
  path: /art_prix/
  controller: App\Controller\IndexController::articlesParPrix
  methods: [GET,POST]